/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe.gltf --transform 
Files: shoe.gltf [21KB] > /home/memnoc/Code/3d-showcase/public/shoe-transformed.glb [260.48KB] (-1140%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/shoe-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shoe.geometry} material={materials.mesh} />
      <mesh geometry={nodes.shoe_1.geometry} material={materials.caps} />
      <mesh geometry={nodes.shoe_2.geometry} material={materials.laces} />
    </group>
  );
}

useGLTF.preload("/shoe-transformed.glb");
